# Generated by Django 5.1.5 on 2026-01-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('desserts', 'Desserts'), ('vegetarian', 'Vegetarian')], max_length=20)),
                ('cooking_time', models.IntegerField(help_text='Time in minutes')),
                ('servings', models.IntegerField()),
                ('ingredients', models.TextField(help_text='Enter each ingredient on a new line')),
                ('instructions', models.TextField(help_text='Enter cooking instructions, one step per line')),
                ('emoji', models.CharField(default='🍽️', help_text='Emoji for the recipe', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
